services:
  - type: web
    name: yt-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt && apt-get install -y ffmpeg
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 7860
